AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String

Resources:
  # todo: rather than a user, introduce Github OIDC into bootstrap somehow
  DeployInfraUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${ProjectName}-DeployInfraUser

  # todo: tailor this down to minimal set of policies
  DeployInfraPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      PolicyName: !Sub ${ProjectName}-DeployInfraPolicy
      Users:
        - !Ref DeployInfraUser
