AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub ${AWS::StackName}

  Nonprod:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: nonprod
      EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: nonprod
      Stage: DEVELOPMENT

  Prod:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: prod
      EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: prod
      Stage: PRODUCTION
