name: UI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - api/**
  #     - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ui test:withIntegration

  deploy-nonprod:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - name: Deploy
        run: pnpm --filter ui deploy:nonprod

  e2e-nonprod:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: deploy-nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - name: End to End Tests
        run: |
          pnpm --filter ui exec playwright install --with-deps
          pnpm --filter ui e2e:nonprod
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  deploy-prod:
    needs: e2e-nonprod
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - run: pnpm install --frozen-lockfile
      - name: Deploy
        run: pnpm --filter ui deploy:prod

  e2e-prod:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - name: End to End Tests
        run: |
          pnpm --filter ui exec playwright install --with-deps
          pnpm --filter ui e2e:prod
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
